import { useCallback, useEffect, useState } from 'react'
import { adminApi } from '@/api/admin/adminApi'
import { apiMessage } from '@/api/http'
import ErrorAlert from '@/shared/components/ErrorAlert'
import Loading from '@/shared/components/Loading'
import { dateTimeVN } from '@/shared/utils/format'
const EMPTY={content:[],page:0,totalElements:0,totalPages:0,first:true,last:true}
export default function AdminPropertiesPage(){
 const [data,setData]=useState(EMPTY),[managers,setManagers]=useState([]),[filters,setFilters]=useState({keyword:'',status:''}),[applied,setApplied]=useState({}),[page,setPage]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[working,setWorking]=useState(null)
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [props,users]=await Promise.all([adminApi.properties({page,size:20,...applied}),adminApi.users({role:'HOTEL_MANAGER',status:'ACTIVE',page:0,size:100})]);setData({...EMPTY,...props});setManagers(users.content||[])}catch(e){setError(apiMessage(e))}finally{setLoading(false)}},[page,applied])
 useEffect(()=>{load()},[load])
 const update=async(p,payload)=>{setWorking(p.id);setError('');setNotice('');try{await adminApi.moderateProperty(p.id,payload);setNotice(`Đã cập nhật ${p.name}.`);await load()}catch(e){setError(apiMessage(e))}finally{setWorking(null)}}
 return <main className="admin-page"><header className="admin-page-header"><div><p>Marketplace governance</p><h1>Kiểm duyệt chỗ nghỉ</h1><span>Duyệt trạng thái, gắn nổi bật và phân công manager sở hữu.</span></div><strong>{data.totalElements} chỗ nghỉ</strong></header><ErrorAlert message={error}/>{notice&&<div className="alert alert-success">{notice}</div>}
 <form className="admin-filters property-filters" onSubmit={e=>{e.preventDefault();setPage(0);setApplied(Object.fromEntries(Object.entries(filters).filter(([,v])=>v)))}}><label>Tìm kiếm<input value={filters.keyword} onChange={e=>setFilters({...filters,keyword:e.target.value})} placeholder="Tên, thành phố, slug, owner"/></label><label>Trạng thái<select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Tất cả</option><option>DRAFT</option><option>ACTIVE</option><option>SUSPENDED</option><option>ARCHIVED</option></select></label><button className="btn btn-primary">Lọc</button></form>
 {loading?<Loading/>:<section className="admin-panel"><div className="admin-table-wrap"><table className="admin-table property-admin-table"><thead><tr><th>Chỗ nghỉ</th><th>Manager</th><th>Phòng/Booking</th><th>Nổi bật</th><th>Trạng thái</th><th>Ngày tạo</th></tr></thead><tbody>{data.content.map(p=><tr key={p.id}><td><strong>{p.name}</strong><small>{p.propertyType} · {p.city}, {p.country}</small><small>{p.slug}</small></td><td><select disabled={working===p.id} value={p.ownerId||''} onChange={e=>update(p,e.target.value?{ownerId:e.target.value,clearOwner:false}:{clearOwner:true})}><option value="">Chưa phân công</option>{managers.map(m=><option key={m.id} value={m.id}>{m.fullName} · {m.email}</option>)}</select></td><td>{p.roomTypeCount} phòng<small>{p.bookingCount} booking</small></td><td><label className="admin-toggle"><input type="checkbox" checked={p.featured} disabled={working===p.id} onChange={e=>update(p,{featured:e.target.checked})}/><span>{p.featured?'Có':'Không'}</span></label></td><td><select disabled={working===p.id} value={p.status} onChange={e=>update(p,{status:e.target.value})}><option>DRAFT</option><option>ACTIVE</option><option>SUSPENDED</option><option>ARCHIVED</option></select></td><td>{dateTimeVN(p.createdAt)}</td></tr>)}</tbody></table></div></section>}
 {data.totalPages>1&&<nav className="pagination admin-pagination"><button disabled={data.first} onClick={()=>setPage(v=>v-1)}>← Trước</button><span>Trang {page+1}/{data.totalPages}</span><button disabled={data.last} onClick={()=>setPage(v=>v+1)}>Sau →</button></nav>}</main>
}
