-- =============================================================
-- RoomEase - Supabase PostgreSQL schema
-- Run once in Supabase SQL Editor on a new project.
-- React never connects directly to these tables; Spring Boot is the API layer.
-- =============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 1. Accounts managed by Spring Security/JWT (not Supabase Auth).
CREATE TABLE app_users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    full_name VARCHAR(120) NOT NULL,
    email VARCHAR(180) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    phone VARCHAR(30),
    avatar_url VARCHAR(800),
    google_subject VARCHAR(255),
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    role VARCHAR(30) NOT NULL DEFAULT 'CUSTOMER',
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_app_users_role CHECK (role IN ('CUSTOMER', 'HOTEL_MANAGER', 'ADMIN')),
    CONSTRAINT ck_app_users_status CHECK (status IN ('ACTIVE', 'BLOCKED', 'PENDING'))
);
CREATE UNIQUE INDEX uk_app_users_email_lower ON app_users (LOWER(email));
CREATE UNIQUE INDEX uk_app_users_google_subject ON app_users (google_subject) WHERE google_subject IS NOT NULL;
CREATE INDEX idx_app_users_role_status ON app_users (role, status);
CREATE TRIGGER trg_app_users_updated_at
BEFORE UPDATE ON app_users FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 2. Accommodation/property master data.
CREATE TABLE properties (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id UUID,
    name VARCHAR(200) NOT NULL,
    slug VARCHAR(220) NOT NULL,
    property_type VARCHAR(40) NOT NULL,
    description TEXT,
    address_line VARCHAR(255) NOT NULL,
    ward VARCHAR(120),
    district VARCHAR(120),
    city VARCHAR(120) NOT NULL,
    province VARCHAR(120),
    country VARCHAR(100) NOT NULL DEFAULT 'Việt Nam',
    postal_code VARCHAR(30),
    latitude NUMERIC(10, 7),
    longitude NUMERIC(10, 7),
    star_rating INTEGER NOT NULL DEFAULT 0,
    review_score NUMERIC(3, 1) NOT NULL DEFAULT 0,
    review_count INTEGER NOT NULL DEFAULT 0,
    check_in_from TIME NOT NULL DEFAULT '14:00',
    check_in_until TIME,
    check_out_from TIME,
    check_out_until TIME NOT NULL DEFAULT '12:00',
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_properties_owner FOREIGN KEY (owner_id) REFERENCES app_users(id) ON DELETE SET NULL,
    CONSTRAINT uk_properties_slug UNIQUE (slug),
    CONSTRAINT ck_properties_type CHECK (property_type IN ('HOTEL', 'APARTMENT', 'RESORT', 'VILLA', 'HOSTEL', 'HOMESTAY')),
    CONSTRAINT ck_properties_stars CHECK (star_rating BETWEEN 0 AND 5),
    CONSTRAINT ck_properties_review_score CHECK (review_score BETWEEN 0 AND 10),
    CONSTRAINT ck_properties_review_count CHECK (review_count >= 0),
    CONSTRAINT ck_properties_status CHECK (status IN ('DRAFT', 'ACTIVE', 'SUSPENDED', 'ARCHIVED'))
);
CREATE INDEX idx_properties_destination ON properties (LOWER(city), LOWER(country), status);
CREATE INDEX idx_properties_name_trgm ON properties USING GIN (LOWER(name) gin_trgm_ops);
CREATE INDEX idx_properties_city_trgm ON properties USING GIN (LOWER(city) gin_trgm_ops);
CREATE INDEX idx_properties_type_stars ON properties (property_type, star_rating, status);
CREATE INDEX idx_properties_featured ON properties (featured, status);
CREATE TRIGGER trg_properties_updated_at
BEFORE UPDATE ON properties FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE property_images (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    property_id UUID NOT NULL,
    image_url VARCHAR(1000) NOT NULL,
    alt_text VARCHAR(255),
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_cover BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_property_images_property FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE,
    CONSTRAINT ck_property_images_sort CHECK (sort_order >= 0)
);
CREATE INDEX idx_property_images_order ON property_images (property_id, is_cover DESC, sort_order);

CREATE TABLE amenities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(120) NOT NULL,
    category VARCHAR(50) NOT NULL,
    icon VARCHAR(80),
    CONSTRAINT uk_amenities_code UNIQUE (code),
    CONSTRAINT ck_amenities_category CHECK (category IN ('POPULAR', 'ROOM', 'BATHROOM', 'FOOD', 'SERVICE', 'ACCESSIBILITY', 'ACTIVITY', 'SAFETY'))
);

CREATE TABLE property_amenities (
    property_id UUID NOT NULL,
    amenity_id BIGINT NOT NULL,
    PRIMARY KEY (property_id, amenity_id),
    CONSTRAINT fk_property_amenities_property FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE,
    CONSTRAINT fk_property_amenities_amenity FOREIGN KEY (amenity_id) REFERENCES amenities(id) ON DELETE CASCADE
);
CREATE INDEX idx_property_amenities_amenity ON property_amenities (amenity_id, property_id);

CREATE TABLE property_policies (
    property_id UUID PRIMARY KEY,
    children_allowed BOOLEAN NOT NULL DEFAULT TRUE,
    pets_policy VARCHAR(30) NOT NULL DEFAULT 'NOT_ALLOWED',
    smoking_policy VARCHAR(30) NOT NULL DEFAULT 'NON_SMOKING',
    parties_allowed BOOLEAN NOT NULL DEFAULT FALSE,
    quiet_hours_from TIME,
    quiet_hours_until TIME,
    age_restriction INTEGER,
    extra_bed_policy TEXT,
    important_information TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_property_policies_property FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE,
    CONSTRAINT ck_property_policies_pets CHECK (pets_policy IN ('ALLOWED', 'ON_REQUEST', 'NOT_ALLOWED')),
    CONSTRAINT ck_property_policies_smoking CHECK (smoking_policy IN ('NON_SMOKING', 'DESIGNATED_AREAS', 'ALLOWED')),
    CONSTRAINT ck_property_policies_age CHECK (age_restriction IS NULL OR age_restriction BETWEEN 0 AND 99)
);
CREATE TRIGGER trg_property_policies_updated_at
BEFORE UPDATE ON property_policies FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 3. Sellable room types and rate plans.
CREATE TABLE room_types (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    property_id UUID NOT NULL,
    code VARCHAR(60) NOT NULL,
    name VARCHAR(160) NOT NULL,
    description TEXT,
    room_size_sqm NUMERIC(7, 2),
    max_adults INTEGER NOT NULL,
    max_children INTEGER NOT NULL DEFAULT 0,
    max_guests INTEGER NOT NULL,
    total_rooms INTEGER NOT NULL,
    bed_summary VARCHAR(255) NOT NULL,
    bathroom_count INTEGER NOT NULL DEFAULT 1,
    view_name VARCHAR(120),
    smoking_allowed BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_room_types_property FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE,
    CONSTRAINT uk_room_types_property_code UNIQUE (property_id, code),
    CONSTRAINT ck_room_types_size CHECK (room_size_sqm IS NULL OR room_size_sqm > 0),
    CONSTRAINT ck_room_types_capacity CHECK (max_adults > 0 AND max_children >= 0 AND max_guests > 0),
    CONSTRAINT ck_room_types_total CHECK (total_rooms > 0),
    CONSTRAINT ck_room_types_bathrooms CHECK (bathroom_count > 0)
);
CREATE INDEX idx_room_types_property_active ON room_types (property_id, active);
CREATE TRIGGER trg_room_types_updated_at
BEFORE UPDATE ON room_types FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE room_type_images (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    room_type_id UUID NOT NULL,
    image_url VARCHAR(1000) NOT NULL,
    alt_text VARCHAR(255),
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_room_type_images_room FOREIGN KEY (room_type_id) REFERENCES room_types(id) ON DELETE CASCADE,
    CONSTRAINT ck_room_type_images_sort CHECK (sort_order >= 0)
);
CREATE INDEX idx_room_type_images_order ON room_type_images (room_type_id, sort_order);

CREATE TABLE room_amenities (
    room_type_id UUID NOT NULL,
    amenity_id BIGINT NOT NULL,
    PRIMARY KEY (room_type_id, amenity_id),
    CONSTRAINT fk_room_amenities_room FOREIGN KEY (room_type_id) REFERENCES room_types(id) ON DELETE CASCADE,
    CONSTRAINT fk_room_amenities_amenity FOREIGN KEY (amenity_id) REFERENCES amenities(id) ON DELETE CASCADE
);

CREATE TABLE rate_plans (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    room_type_id UUID NOT NULL,
    code VARCHAR(60) NOT NULL,
    name VARCHAR(160) NOT NULL,
    meal_plan VARCHAR(40) NOT NULL DEFAULT 'ROOM_ONLY',
    cancellation_type VARCHAR(40) NOT NULL,
    cancellation_days INTEGER NOT NULL DEFAULT 0,
    prepayment_type VARCHAR(40) NOT NULL DEFAULT 'NONE',
    refundable BOOLEAN NOT NULL DEFAULT TRUE,
    pay_at_property BOOLEAN NOT NULL DEFAULT TRUE,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_rate_plans_room FOREIGN KEY (room_type_id) REFERENCES room_types(id) ON DELETE CASCADE,
    CONSTRAINT uk_rate_plans_room_code UNIQUE (room_type_id, code),
    CONSTRAINT ck_rate_plans_meal CHECK (meal_plan IN ('ROOM_ONLY', 'BREAKFAST_INCLUDED', 'HALF_BOARD', 'FULL_BOARD', 'ALL_INCLUSIVE')),
    CONSTRAINT ck_rate_plans_cancellation CHECK (cancellation_type IN ('FREE_UNTIL_DAYS', 'NON_REFUNDABLE', 'FLEXIBLE')),
    CONSTRAINT ck_rate_plans_cancellation_days CHECK (cancellation_days >= 0),
    CONSTRAINT ck_rate_plans_prepayment CHECK (prepayment_type IN ('NONE', 'FULL', 'FIRST_NIGHT', 'PERCENTAGE'))
);
CREATE INDEX idx_rate_plans_room_active ON rate_plans (room_type_id, active);
CREATE TRIGGER trg_rate_plans_updated_at
BEFORE UPDATE ON rate_plans FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Inventory is room-type level for each stay date.
CREATE TABLE inventory_calendar (
    room_type_id UUID NOT NULL,
    stay_date DATE NOT NULL,
    allotment INTEGER NOT NULL,
    reserved_rooms INTEGER NOT NULL DEFAULT 0,
    stop_sell BOOLEAN NOT NULL DEFAULT FALSE,
    closed_to_arrival BOOLEAN NOT NULL DEFAULT FALSE,
    closed_to_departure BOOLEAN NOT NULL DEFAULT FALSE,
    min_stay INTEGER NOT NULL DEFAULT 1,
    max_stay INTEGER,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (room_type_id, stay_date),
    CONSTRAINT fk_inventory_calendar_room FOREIGN KEY (room_type_id) REFERENCES room_types(id) ON DELETE CASCADE,
    CONSTRAINT ck_inventory_allotment CHECK (allotment >= 0),
    CONSTRAINT ck_inventory_reserved CHECK (reserved_rooms >= 0 AND reserved_rooms <= allotment),
    CONSTRAINT ck_inventory_min_stay CHECK (min_stay > 0),
    CONSTRAINT ck_inventory_max_stay CHECK (max_stay IS NULL OR max_stay >= min_stay)
);
CREATE INDEX idx_inventory_date_room ON inventory_calendar (stay_date, room_type_id);
CREATE INDEX idx_inventory_available ON inventory_calendar (room_type_id, stay_date, stop_sell, reserved_rooms, allotment);
CREATE TRIGGER trg_inventory_calendar_updated_at
BEFORE UPDATE ON inventory_calendar FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Prices are rate-plan level for each stay date.
CREATE TABLE rate_calendar (
    rate_plan_id UUID NOT NULL,
    stay_date DATE NOT NULL,
    price NUMERIC(15, 2) NOT NULL,
    original_price NUMERIC(15, 2),
    currency VARCHAR(3) NOT NULL DEFAULT 'VND',
    available BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (rate_plan_id, stay_date),
    CONSTRAINT fk_rate_calendar_plan FOREIGN KEY (rate_plan_id) REFERENCES rate_plans(id) ON DELETE CASCADE,
    CONSTRAINT ck_rate_calendar_price CHECK (price > 0),
    CONSTRAINT ck_rate_calendar_original CHECK (original_price IS NULL OR original_price >= price),
    CONSTRAINT ck_rate_calendar_currency CHECK (currency ~ '^[A-Z]{3}$')
);
CREATE INDEX idx_rate_calendar_date_plan ON rate_calendar (stay_date, rate_plan_id, available);
CREATE TRIGGER trg_rate_calendar_updated_at
BEFORE UPDATE ON rate_calendar FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 4. Reservations and payments.
CREATE TABLE bookings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_code VARCHAR(30) NOT NULL,
    user_id UUID NOT NULL,
    property_id UUID NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    payment_status VARCHAR(30) NOT NULL DEFAULT 'UNPAID',
    check_in DATE NOT NULL,
    check_out DATE NOT NULL,
    nights INTEGER NOT NULL,
    adults INTEGER NOT NULL,
    children INTEGER NOT NULL DEFAULT 0,
    rooms_count INTEGER NOT NULL,
    subtotal NUMERIC(15, 2) NOT NULL,
    discount_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    tax_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    total_amount NUMERIC(15, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'VND',
    guest_full_name VARCHAR(160) NOT NULL,
    guest_email VARCHAR(180) NOT NULL,
    guest_phone VARCHAR(30) NOT NULL,
    special_request VARCHAR(1500),
    cancellation_deadline TIMESTAMPTZ,
    source VARCHAR(30) NOT NULL DEFAULT 'WEB',
    cancelled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_bookings_code UNIQUE (booking_code),
    CONSTRAINT fk_bookings_user FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_bookings_property FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE RESTRICT,
    CONSTRAINT ck_bookings_status CHECK (status IN ('PENDING', 'CONFIRMED', 'CHECKED_IN', 'COMPLETED', 'CANCELLED', 'NO_SHOW')),
    CONSTRAINT ck_bookings_payment_status CHECK (payment_status IN ('UNPAID', 'PENDING', 'PAID', 'PARTIALLY_REFUNDED', 'REFUNDED', 'FAILED', 'NOT_REQUIRED')),
    CONSTRAINT ck_bookings_dates CHECK (check_out > check_in AND nights > 0),
    CONSTRAINT ck_bookings_guests CHECK (adults > 0 AND children >= 0 AND rooms_count > 0),
    CONSTRAINT ck_bookings_money CHECK (subtotal >= 0 AND discount_amount >= 0 AND tax_amount >= 0 AND total_amount >= 0),
    CONSTRAINT ck_bookings_currency CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_bookings_source CHECK (source IN ('WEB', 'MOBILE', 'ADMIN'))
);
CREATE INDEX idx_bookings_user_created ON bookings (user_id, created_at DESC);
CREATE INDEX idx_bookings_property_dates ON bookings (property_id, check_in, check_out, status);
CREATE INDEX idx_bookings_status_created ON bookings (status, created_at DESC);
CREATE TRIGGER trg_bookings_updated_at
BEFORE UPDATE ON bookings FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE booking_rooms (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id UUID NOT NULL,
    room_type_id UUID NOT NULL,
    rate_plan_id UUID NOT NULL,
    room_name_snapshot VARCHAR(160) NOT NULL,
    rate_plan_name_snapshot VARCHAR(160) NOT NULL,
    meal_plan_snapshot VARCHAR(40) NOT NULL,
    cancellation_policy_snapshot TEXT,
    quantity INTEGER NOT NULL,
    adults INTEGER NOT NULL,
    children INTEGER NOT NULL DEFAULT 0,
    unit_price NUMERIC(15, 2) NOT NULL,
    nights INTEGER NOT NULL,
    subtotal NUMERIC(15, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_booking_rooms_booking FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_rooms_room FOREIGN KEY (room_type_id) REFERENCES room_types(id) ON DELETE RESTRICT,
    CONSTRAINT fk_booking_rooms_plan FOREIGN KEY (rate_plan_id) REFERENCES rate_plans(id) ON DELETE RESTRICT,
    CONSTRAINT ck_booking_rooms_quantity CHECK (quantity > 0),
    CONSTRAINT ck_booking_rooms_guests CHECK (adults > 0 AND children >= 0),
    CONSTRAINT ck_booking_rooms_money CHECK (unit_price > 0 AND subtotal >= 0),
    CONSTRAINT ck_booking_rooms_nights CHECK (nights > 0)
);
CREATE INDEX idx_booking_rooms_booking ON booking_rooms (booking_id);
CREATE INDEX idx_booking_rooms_inventory ON booking_rooms (room_type_id, rate_plan_id);

CREATE TABLE booking_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id UUID NOT NULL,
    from_status VARCHAR(30),
    to_status VARCHAR(30) NOT NULL,
    note VARCHAR(500),
    changed_by UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_booking_history_booking FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_history_user FOREIGN KEY (changed_by) REFERENCES app_users(id) ON DELETE SET NULL
);
CREATE INDEX idx_booking_history_booking ON booking_status_history (booking_id, created_at);

CREATE TABLE payments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id UUID NOT NULL,
    provider VARCHAR(50) NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    amount NUMERIC(15, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'VND',
    transaction_ref VARCHAR(160),
    paid_at TIMESTAMPTZ,
    failure_reason VARCHAR(500),
    raw_response JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_payments_booking FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE,
    CONSTRAINT ck_payments_status CHECK (status IN ('PENDING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'REFUNDED', 'PARTIALLY_REFUNDED')),
    CONSTRAINT ck_payments_amount CHECK (amount >= 0),
    CONSTRAINT ck_payments_currency CHECK (currency ~ '^[A-Z]{3}$')
);
CREATE UNIQUE INDEX uk_payments_transaction_ref ON payments (transaction_ref) WHERE transaction_ref IS NOT NULL;
CREATE INDEX idx_payments_booking ON payments (booking_id, created_at DESC);
CREATE TRIGGER trg_payments_updated_at
BEFORE UPDATE ON payments FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 5. Reviews and favourites.
CREATE TABLE reviews (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id UUID NOT NULL,
    property_id UUID NOT NULL,
    user_id UUID NOT NULL,
    score NUMERIC(3, 1) NOT NULL,
    title VARCHAR(180),
    content TEXT,
    staff_score NUMERIC(3, 1),
    cleanliness_score NUMERIC(3, 1),
    location_score NUMERIC(3, 1),
    comfort_score NUMERIC(3, 1),
    value_score NUMERIC(3, 1),
    status VARCHAR(30) NOT NULL DEFAULT 'PUBLISHED',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_reviews_booking UNIQUE (booking_id),
    CONSTRAINT fk_reviews_booking FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_property FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE,
    CONSTRAINT ck_reviews_score CHECK (score BETWEEN 1 AND 10),
    CONSTRAINT ck_reviews_subscores CHECK (
        (staff_score IS NULL OR staff_score BETWEEN 1 AND 10) AND
        (cleanliness_score IS NULL OR cleanliness_score BETWEEN 1 AND 10) AND
        (location_score IS NULL OR location_score BETWEEN 1 AND 10) AND
        (comfort_score IS NULL OR comfort_score BETWEEN 1 AND 10) AND
        (value_score IS NULL OR value_score BETWEEN 1 AND 10)
    ),
    CONSTRAINT ck_reviews_status CHECK (status IN ('PENDING', 'PUBLISHED', 'HIDDEN'))
);
CREATE INDEX idx_reviews_property ON reviews (property_id, status, created_at DESC);
CREATE TRIGGER trg_reviews_updated_at
BEFORE UPDATE ON reviews FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE favourites (
    user_id UUID NOT NULL,
    property_id UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, property_id),
    CONSTRAINT fk_favourites_user FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE,
    CONSTRAINT fk_favourites_property FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE
);
CREATE INDEX idx_favourites_property ON favourites (property_id);

-- Recalculate cached property review score after review changes.
CREATE OR REPLACE FUNCTION refresh_property_review_summary()
RETURNS TRIGGER AS $$
DECLARE
    target_property UUID;
BEGIN
    IF TG_OP = 'DELETE' THEN
        target_property := OLD.property_id;
    ELSE
        target_property := NEW.property_id;
    END IF;
    UPDATE properties p
       SET review_score = COALESCE(s.avg_score, 0),
           review_count = COALESCE(s.review_count, 0),
           updated_at = NOW()
      FROM (
        SELECT property_id, ROUND(AVG(score), 1) AS avg_score, COUNT(*)::INTEGER AS review_count
          FROM reviews
         WHERE property_id = target_property AND status = 'PUBLISHED'
         GROUP BY property_id
      ) s
     WHERE p.id = target_property;

    IF NOT FOUND THEN
        UPDATE properties SET review_score = 0, review_count = 0, updated_at = NOW()
        WHERE id = target_property;
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_reviews_refresh_property
AFTER INSERT OR UPDATE OR DELETE ON reviews
FOR EACH ROW EXECUTE FUNCTION refresh_property_review_summary();

-- Supabase public schema is exposed by Data API. Browser roles get no direct table access.
ALTER TABLE app_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE property_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE amenities ENABLE ROW LEVEL SECURITY;
ALTER TABLE property_amenities ENABLE ROW LEVEL SECURITY;
ALTER TABLE property_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE room_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE room_type_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE room_amenities ENABLE ROW LEVEL SECURITY;
ALTER TABLE rate_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_calendar ENABLE ROW LEVEL SECURITY;
ALTER TABLE rate_calendar ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE booking_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE booking_status_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE favourites ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM anon, authenticated;

COMMENT ON TABLE inventory_calendar IS 'Daily sellable inventory at room-type level. Availability = allotment - reserved_rooms.';
COMMENT ON TABLE rate_calendar IS 'Daily price for one rate plan. A room type may have flexible and non-refundable rate plans.';
COMMENT ON TABLE booking_rooms IS 'Immutable booking line snapshots protect historical prices and policies after hotel data changes.';
